apiVersion: apps/v1
kind: Deployment
metadata:
  name: simpleblogapi
spec:
  selector:
    matchLabels:
      component: web
  template:
    metadata:
      labels:
        component: web
    spec:
      containers:
      - name: simpleblogapi
        image: purnimagarg09/blog_api
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 3000
        env:
            - name: POSTGRES_USERNAME
              value: postgres
            - name: POSTGRES_PASSWORD
              value: postgres_password
            - name: POSTGRES_HOST
              value: postgres-cluster-ip-service  
            - name: POSTGRES_DB
              value: simple_blog_api
            - name: POSTGRES_PORT
              value: "5432"
